version: '1'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emContainer
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/em
      - SPRING_DATASOURCE_USERNAME=loren
      - SPRING_DATASOURCE_PASSWORD=loren
    ports:
      - "8080:8080"

  db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: loren
      POSTGRES_DB: em
      POSTGRES_USER: loren
    ports:
      - "5432:5432"
    volumes:
    - ./data:/data